### ISSUE TITLE
İstitastik özelliği

### ISSUE THREAD

**Issue by EchoBilisim** [realsuayip/django-sozluk#45]
Merhaba yazılım çok güzel ve stabil olarak çalışıyor bir kaç sorum olacak 
1. mail ayarı nerden yapılıyor smtp ayarlarının yapılması için nerelere müdahale edebilirim bu konuda bilgilendirirseniz çok sevinirim.
Bu sitenin belli başlı ayarlarını panelden yapılsa güzel olurdu logo ekleme smtp ayarların yapılması için ayar kısmı olursa güzel olurdu bence.
Smtp ayarlarını yaptım ancak mail filan gitmiyor.
2. Yönetim panelinde İstitastik seçeneği olursa güzel olur panelden kaç üye kaç başlık kaç entry var gibi bir seçenek olsa çok güzel olur diye düşünüyorum.
Şimdiden teşekkür ederim.

3. Site bazen konu eklerken veya başka bir işlem yaparken sunucu hatası diye bir hata veriyor bunu neden yapar acaba

**Comment by realsuayip** [comment]
1. Env dosyalarında mail ayarları mevcut, mail gitmiyor ise celery düzgün çalışmıyor olabilir.
2. "Toplam" sayıları ilgili sayfaların en altında görebilirsiniz.
3. Hata mesajı görmeden söylemek zor, log dosyanız/çıktınız varsa yollayabilirsiniz.

**Comment by EchoBilisim** [comment]
Merhaba bu satırlar incelemeniz için yeterlimi acaba ?

`[2022-04-17 14:08:08,987: WARNING/ForkPoolWorker-1] djcelery_email_send_multiple[5d390016-567e-4814-a83b-65e7357b59ad]: Failed to send email message to ['fvrweb@mranker.me'], retrying. (gaierror(-2, 'Name does not resolve'))
[2022-04-17 14:08:08,991: INFO/ForkPoolWorker-1] Task djcelery_email_send_multiple[5d390016-567e-4814-a83b-65e7357b59ad] succeeded in 0.11390154401306063s: 0
[2022-04-17 14:08:08,991: INFO/MainProcess] Task djcelery_email_send_multiple[5d390016-567e-4814-a83b-65e7357b59ad] received
[2022-04-17 14:08:49,246: ERROR/ForkPoolWorker-1] djcelery_email_send_multiple[5d390016-567e-4814-a83b-65e7357b59ad]: Cannot reach CELERY_EMAIL_BACKEND django.core.mail.backends.smtp.EmailBackend
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/djcelery_email/tasks.py", line 40, in send_emails
    conn.open()
  File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 62, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve
[2022-04-17 14:08:49,304: WARNING/ForkPoolWorker-1] djcelery_email_send_multiple[5d390016-567e-4814-a83b-65e7357b59ad]: Failed to send email message to ['fvrweb@mranker.me'], retrying. (gaierror(-2, 'Name does not resolve'))
[2022-04-17 14:08:49,307: INFO/ForkPoolWorker-1] Task djcelery_email_send_multiple[5d390016-567e-4814-a83b-65e7357b59ad] succeeded in 0.11331126501318067s: 0
[2022-04-17 14:08:49,308: INFO/MainProcess] Task djcelery_email_send_multiple[5d390016-567e-4814-a83b-65e7357b59ad] received
[2022-04-17 14:09:29,575: ERROR/ForkPoolWorker-1] djcelery_email_send_multiple[5d390016-567e-4814-a83b-65e7357b59ad]: Cannot reach CELERY_EMAIL_BACKEND django.core.mail.backends.smtp.EmailBackend
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/djcelery_email/tasks.py", line 40, in send_emails
    conn.open()
  File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 62, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve
[2022-04-17 14:09:29,634: WARNING/ForkPoolWorker-1] djcelery_email_send_multiple[5d390016-567e-4814-a83b-65e7357b59ad]: Failed to send email message to ['fvrweb@mranker.me'], retrying. (gaierror(-2, 'Name does not resolve'))
[2022-04-17 14:09:29,637: INFO/ForkPoolWorker-1] Task djcelery_email_send_multiple[5d390016-567e-4814-a83b-65e7357b59ad] succeeded in 0.1156656020320952s: 0
[2022-04-17 14:09:29,638: INFO/MainProcess] Task djcelery_email_send_multiple[5d390016-567e-4814-a83b-65e7357b59ad] received
[2022-04-17 14:10:09,901: ERROR/ForkPoolWorker-1] djcelery_email_send_multiple[5d390016-567e-4814-a83b-65e7357b59ad]: Cannot reach CELERY_EMAIL_BACKEND django.core.mail.backends.smtp.EmailBackend
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/djcelery_email/tasks.py", line 40, in send_emails
    conn.open()
  File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 62, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve
[2022-04-17 14:10:09,954: WARNING/ForkPoolWorker-1] djcelery_email_send_multiple[5d390016-567e-4814-a83b-65e7357b59ad]: Failed to send email message to ['fvrweb@mranker.me'], retrying. (gaierror(-2, 'Name does not resolve'))
[2022-04-17 14:10:09,955: ERROR/ForkPoolWorker-1] Task djcelery_email_send_multiple[5d390016-567e-4814-a83b-65e7357b59ad] raised unexpected: gaierror(-2, 'Name does not resolve')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/djcelery_email/tasks.py", line 57, in send_emails
    send_emails.retry([[message], combined_kwargs], exc=e, throw=False)
  File "/usr/local/lib/python3.8/site-packages/celery/app/task.py", line 717, in retry
    raise_with_context(exc)
  File "/usr/local/lib/python3.8/site-packages/djcelery_email/tasks.py", line 48, in send_emails
    sent = conn.send_messages([dict_to_email(message)])
  File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 102, in send_messages
    new_conn_created = self.open()
  File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 62, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve
[2022-04-17 15:36:50,940: INFO/MainProcess] Task dictionary.tasks.purge_reports[1e68b547-15a1-4538-81cc-c3416a5ec540] received
[2022-04-17 15:36:50,950: INFO/ForkPoolWorker-1] Task dictionary.tasks.purge_reports[1e68b547-15a1-4538-81cc-c3416a5ec540] succeeded in 0.009129682963248342s: None
[2022-04-17 15:36:51,027: INFO/MainProcess] Task dictionary.tasks.purge_images[80753d18-056a-4dd5-a736-35048ff87def] received
[2022-04-17 15:36:51,035: INFO/ForkPoolWorker-1] Task dictionary.tasks.purge_images[80753d18-056a-4dd5-a736-35048ff87def] succeeded in 0.007004635001067072s: None
[2022-04-17 17:36:51,201: INFO/MainProcess] Task dictionary.tasks.commit_user_deletions[725e2dc1-977f-46d1-9cff-b7284379447d] received
[2022-04-17 17:36:51,215: ERROR/ForkPoolWorker-1] Task dictionary.tasks.commit_user_deletions[725e2dc1-977f-46d1-9cff-b7284379447d] raised unexpected: DoesNotExist('Author matching query does not exist.')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/dictionary/tasks.py", line 54, in commit_user_deletions
    AccountTerminationQueue.objects.commit_terminations()
  File "/usr/src/app/dictionary/models/managers/author.py", line 69, in commit_terminations
    self._private_user = get_generic_privateuser()
  File "/usr/src/app/dictionary/utils/__init__.py", line 114, in get_generic_privateuser
    return get_user_model().objects.get(username=settings.GENERIC_PRIVATEUSER_USERNAME)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
dictionary.models.author.Author.DoesNotExist: Author matching query does not exist.
`
