### ISSUE TITLE
django.db.migrations.exceptions.InvalidBasesError in production deployment

### ISSUE THREAD

**Issue by jsdev11** [realsuayip/django-sozluk#64]
I can run the script in my localhost with Docker and there is no problem at all but when try to run it in a server, I get this error:

```
django.db.migrations.exceptions.InvalidBasesError: Cannot resolve bases for [<ModelState: 'dictionary.MetaFlatPage'>]
This can happen if you are inheriting models from an app with migrations (e.g. contrib.auth)
 in an app with no migrations; see https://docs.djangoproject.com/en/3.2/topics/migrations/#dependencies for more
```

then a couple of:
```
django.db.utils.ProgrammingError: relation "dictionary_author" does not exist
LINE 1: SELECT (1) AS "a" FROM "dictionary_author" WHERE "dictionary...
                               ^
```

This seems the second command in "scripts/setup.sh": `python mange.py migrate`. I also run `makemigrations` and `migrate` in web container, same error. Also, `makemigrations` returns: "PostgresSQL is up. No changes detected".

Long error message:
```
Starting initial setup...
No changes detected
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, flatpages, sessions, sites
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 202, in handle
    pre_migrate_apps = pre_migrate_state.apps
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/state.py", line 208, in apps
    return StateApps(self.real_apps, self.models)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/state.py", line 270, in __init__
    self.render_multiple([*models.values(), *self.real_models])
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/state.py", line 309, in render_multiple
    raise InvalidBasesError(
django.db.migrations.exceptions.InvalidBasesError: Cannot resolve bases for [<ModelState: 'dictionary.MetaFlatPage'>]
This can happen if you are inheriting models from an app with migrations (e.g. contrib.auth)
 in an app with no migrations; see https://docs.djangoproject.com/en/3.2/topics/migrations/#dependencies for more
...
...
...
django.db.utils.ProgrammingError: relation "dictionary_author" does not exist
LINE 1: SELECT (1) AS "a" FROM "dictionary_author" WHERE "dictionary...
```

**Comment by jsdev11** [comment]
Actually this is not about changes at all. The problem is using this repo in anotoher repo. For example, even copying & pasting this project files to another repo (in another GitHub account) will not work. Something funky is going on...

I tried two different computers and three different GitHub accounts and countless of repos to install the script but the result was always the same error. This script is only installable from this direct repo.

Oh, another option is forking this repo but that's all. @realsuayip  if you can explain why is that, that would be great. Is there any restriction I am not aware of?

**Comment by realsuayip** [comment]
You need to run setup script in prod setup, maybe you missed that?

**Comment by jsdev11** [comment]
I don't think it is about running setup script in prod. I do follow the same steps for both repos (without any single change, both are absolutely identical). The repo I forked is working, but the other repo I cloned does not work. Maybe this is something related to my dev environment setup (although I highly suspect), I'll close this issue.
